### ISSUE TITLE
Issue: No such file or directory

### ISSUE THREAD

**Issue by adrastee** [NVISOsecurity/evtx-hunter#4]
Hello,
Windows 10 issue with Python 3.8.0 :

python evtx_hunter.py c:\Windows\System32\winevt\Logs
```
2021-11-01 17:18:04,220 - evtx-hunter - INFO - started evtx-hunter
Traceback (most recent call last):
  File "evtx_hunter.py", line 100, in <module>
    main()
  File "evtx_hunter.py", line 36, in main
    evtxloader.load_evtx_files()
  File "evtx-hunter-main\app\helpers\evtx_loader.py", line 63, in load_evtx_files
    with open(vars.TMP_DIR + "files.json", "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\x\\Desktop\\evtx-hunter-main\\app/../tmp/files.json'

```

**Comment by adrastee** [comment]
"tmp" folder created.
